# Generated by Django 5.1.3 on 2025-07-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='bbox_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
