# Generated by Django 5.1.3 on 2025-07-30 08:21

import apps.scans.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_scan_bbox_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stl_file', models.FileField(blank=True, null=True, upload_to=apps.scans.models.patient_scan_upload_to)),
                ('depth_map_8bit', models.FileField(blank=True, null=True, upload_to=apps.scans.models.patient_scan_upload_to)),
                ('depth_map_16bit', models.FileField(blank=True, null=True, upload_to=apps.scans.models.patient_scan_upload_to)),
                ('preview_image', models.FileField(blank=True, null=True, upload_to=apps.scans.models.patient_scan_upload_to)),
                ('volume_estimate', models.FloatField(blank=True, null=True)),
                ('processing_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='scans.scan')),
            ],
        ),
    ]
