Table users {
  id integer [primary key]
  first_name varchar
  last_name varchar
  email varchar [unique]
  password varchar
  created_at timestamp
}

Table patients {
  id integer [primary key]
  user_id integer [not null, ref: > users.id]
  first_name varchar
  last_name varchar
  id_number varchar [note: 'NRIC or Passport Number']
  contact_no varchar
  created_at timestamp
}

Table wound_scans {
  id integer [primary key]
  patient_id integer [not null, ref: > patients.id]
  captured_by integer [ref: > users.id]
  scan_datetime timestamp
  image_url varchar
  status varchar [note: 'pending / mesh_processed / files_generated'] // Updated states
  created_at timestamp
}
// does not need 
Table segmentation_results {
  id integer [primary key]
  scan_id integer [not null, ref: > wound_scans.id]
  segmentation_mask_url varchar
  processed_date timestamp
}
// width, height, depth -> X
Table stl_files {
  id integer [primary key]
  scan_id integer [not null, ref: > wound_scans.id]
  file_url varchar [note: 'Downloadable STL file for printing']
  created_date timestamp
}

Table gcode_files {
  id integer [primary key]
  stl_id integer [not null, ref: > stl_files.id]
  file_url varchar [note: 'Generated G-code for printer']
  created_date timestamp
}