# Generated by Django 5.1.3 on 2024-11-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreViews', '0002_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nric',
            field=models.CharField(default=0, max_length=9, unique=True),
            preserve_default=False,
        ),
    ]
